[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"


[tool.pytest.ini_options]
asyncio_mode = 'strict'
log_cli = 1
log_cli_level = 'DEBUG'


[tool.isort]
profile = "google"
