[tool.poetry]
name = "qzemoji"
version = "3.3.2"
description = "Translate Qzone emoji link to text."
authors = ["aioqzone <zzzzss990315@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/aioqzone/QzEmoji"
repository = "https://github.com/aioqzone/QzEmoji"

[tool.poetry.dependencies]
python = "^3.7"
SQLAlchemy = {extras = ["asyncio"], version = "^1.4.32"}
aiosqlite = "~0.17.0"
assetsupdater = {git = "https://github.com/JamzumSum/AssetsUpdater.git", rev = "release"}
PyYAML = "^6.0"
# extras: dev
pre-commit = {version = "^2.20.0", optional = true}
black = {version = "^22.1.0", optional = true}
isort = {version = "^5.10.1", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
pytest-asyncio = "~0.19.0"

[tool.poetry.extras]
dev = [
    "pre-commit",
    "black",
    "isort"
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


# customize begin
[tool.pytest.ini_options]
pythonpath = 'src'
asyncio_mode = 'strict'
log_cli = 1
log_cli_level = 'WARNING'

[tool.isort]
profile = "black"
line_length = 99

[tool.black]
line-length = 99
target-version = ['py37']
