# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Database only

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install .[build]

      - name: Build database and wheel
        run: |
          export PYTHONPATH=$(pwd)/src
          python script/build.py

      - name: Draft a release
        uses: softprops/action-gh-release@v1
        with:
          files: data/emoji.db
          tag_name: $(cat ./src/VERSION)
          body: ${{ github.event.pull_request.body }}
          draft: true
