# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Release and Upload to aioqzone-index

on:
  pull_request_target:
    types:
      - closed
    branches:
      - "beta"
      - "beta/**"
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-upload:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.pull_request.labels.*.name, 'release')
    env:
      GH_TOKEN: ${{ github.token }}
      index-repo: aioqzone/aioqzone-index
    permissions:
      contents: write # release needs write permission
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: poetry

      - name: Build dist and database
        id: build
        run: |
          version=$(poetry version -s)
          echo "version=$version" >> $GITHUB_ENV

          echo "::group::build package"
          poetry build
          echo "::endgroup::"

          echo "::group::install dependencies"
          poetry install --without test
          echo "::endgroup::"

          hash=$(poetry run python script/build.py)
          echo "db-hash=$hash" >> $GITHUB_OUTPUT

      - name: Upload to Release
        id: upload
        uses: JamzumSum/actions/hash-release@master
        with:
          tag: ${{ env.version }}
          files: dist/* data/emoji.db

      - name: replace hash
        id: rehash
        env:
          urls: ${{ steps.upload.outputs.urls }}
          hash: ${{ steps.build.outputs.db-hash }}
        run: |
          urls=$(echo $urls | sed "s/emoji.db#sha256=\w*/emoji.db#sha256=$hash/")
          echo "urls=$urls" >> $GITHUB_OUTPUT

      - name: Add to aioqzone-index
        env:
          urls: ${{ steps.rehash.outputs.urls }}
          GH_TOKEN: ${{ secrets.REPO_TOKEN }} # this is a fine-grained PAT
        run: |
          gh workflow -R ${{ env.index-repo }} run add.yml \
                      -f project=QzEmoji \
                      -f urls="$urls"
