name: Dev CI

on:
  push:
    paths:
      - "src/**"
      - "test/**"
      - ".github/workflows/ci.yml"
      - ".github/workflows/test.yml"
      - "poetry.lock"
    branches:
      - dev
      - dev/**

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '@no-test')"
    uses: ./.github/workflows/test.yml
    with:
      PYTEST_ARGS: test

  merge:
    needs: test
    if: "!contains(github.event.head_commit.message, '@no-pr')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: release
      - name: Get release SHA
        id: sha
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v1
        id: git-cliff
        with:
          config: cliff.toml
          args: -t ${{ needs.test.outputs.package-version }} ${{ steps.sha.outputs.sha }}..HEAD
        env:
          OUTPUT: CHANGELOG.md

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: beta
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: ${{ needs.test.outputs.package-version }}
          pr_template: CHANGELOG.md
